# Generated by Django 5.2 on 2025-05-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_user_banner_image_alter_experience_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skill_icons/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('backend', 'Backend Development'), ('frontend', 'Frontend & Web'), ('database', 'Database & DevOps'), ('hardware', 'Hardware & Embedded Systems'), ('soft', 'Soft Skills'), ('other', 'Other Skills')], default='other', max_length=30),
        ),
    ]
