# Generated by Django 5.2 on 2025-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skill_icon_skill_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skill_icons/'),
        ),
    ]
