# Generated by Django 5.2 on 2025-05-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_service_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='user',
            new_name='user_id',
        ),
    ]
