# Generated by Django 5.2 on 2025-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_user_achievement_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
