# Generated by Django 5.2 on 2025-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_service_icon_service_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('PHP', 'PHP'), ('Python', 'Python'), ('Django', 'Python-Django'), ('C++', 'C++'), ('js', 'Java Script'), ('HTML_CSS', 'HTML/CSS'), ('C++', 'C++'), ('C#', 'C#'), ('React', 'React'), ('Node', 'Node'), ('Flutter', 'Flutter'), ('JAVA', 'JAVA'), ('Electronics', 'Electronics'), ('Arduino', 'Arduino'), ('Academic', 'Academic'), ('MY-SQL', 'MY-SQL'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
