# Generated by Django 5.2 on 2025-05-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projectcategory_remove_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='department_logo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/img/education/department_logo'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_logo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/img/education/institution_logo'),
        ),
    ]
