# Generated by Django 5.2 on 2025-05-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_education_department_logo_education_institution_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classification',
            new_name='Certification',
        ),
    ]
