# Generated by Django 5.2 on 2025-05-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_classification_certification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
