# Generated by Django 5.2 on 2025-05-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_delete_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/img/certificate_images/'),
        ),
        migrations.AddField(
            model_name='education',
            name='certificate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='portfolio.certification'),
        ),
        migrations.AddField(
            model_name='experience',
            name='certificate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.certification'),
        ),
    ]
