# Generated by Django 5.2 on 2025-05-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_certification_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/img/skill_icons/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/img/person/banner_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/img/person/profile_images/'),
        ),
    ]
