# Generated by Django 5.2 on 2025-05-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_skill_icon_alter_user_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tag_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
