# Generated by Django 5.2 on 2025-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_user_tag_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
