# Generated by Django 5.2 on 2025-05-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_user_meta_description_user_meta_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='user_id',
            new_name='user',
        ),
    ]
