# Generated by Django 5.2 on 2025-05-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_rename_user_id_certification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='meta_keywords',
        ),
    ]
