# Generated by Django 5.2 on 2025-05-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_user_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
