# Generated by Django 5.2 on 2025-05-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_user_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp',
        ),
    ]
