# Generated by Django 5.2 on 2025-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_project_tag_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(null=True, upload_to='portfolio/img/certificate_images/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='organization',
            field=models.CharField(max_length=255, null=True, verbose_name='Issuing Organization'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Certification Title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade_standard',
            field=models.CharField(choices=[('4', 'Out of 4'), ('5', 'Out of 5'), ('100', 'Out of 100')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(null=True, upload_to='portfolio/img/skill_icons/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='portfolio/img/person/banner_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='portfolio/img/person/profile_images/'),
        ),
    ]
