# Generated by Django 5.2 on 2025-05-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_rename_certificate_id_education_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/img/experience/institution_logo'),
        ),
    ]
