# Generated by Django 5.2 on 2025-05-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_project_is_featured_alter_experience_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dddd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
