# Generated by Django 5.2 on 2025-05-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_user_dddd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='dddd',
        ),
    ]
