# Generated by Django 5.2 on 2025-06-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_skillcategory_remove_skill_type_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
    ]
