# Generated by Django 5.2 on 2025-06-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
