# Generated by Django 5.2 on 2025-06-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_experience_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='logo',
        ),
    ]
