# Generated by Django 5.2 on 2025-06-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_remove_experience_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AddField(
            model_name='user',
            name='location_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
