# Generated by Django 5.2 on 2025-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_alter_experience_options_user_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
