# Generated by Django 5.2.2 on 2025-06-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0003_user_static_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resume_des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
