# Generated by Django 5.2.2 on 2025-06-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0005_project_hierarchy_project_in_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='hierarchy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='in_resume',
        ),
    ]
