# Generated by Django 5.2.2 on 2025-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0007_experience_resume_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[('On-site', 'on_site'), ('Remote', 'remote'), ('Hybrid', 'hybrid')], default='On-site', max_length=50, null=True),
        ),
    ]
