# Generated by Django 5.2.5 on 2025-08-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0011_rename_project_slug_project_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
    ]
