# Generated by Django 5.2.2 on 2025-06-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='slug',
        ),
    ]
