# Generated by Django 5.2.2 on 2025-06-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resumeproject_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='projects',
        ),
        migrations.DeleteModel(
            name='ResumeProject',
        ),
    ]
