# Generated by Django 5.2.2 on 2025-06-05 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0006_remove_project_hierarchy_remove_project_in_resume'),
        ('resume', '0007_remove_resume_projects_delete_resumeproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.PositiveIntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_spot.project')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
            options={
                'ordering': ['-hierarchy'],
            },
        ),
    ]
