# Generated by Django 5.2.5 on 2025-08-11 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0012_alter_project_managers'),
        ('resume', '0009_alter_resumeproject_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_project', to='landing_spot.project'),
        ),
        migrations.AlterField(
            model_name='resumeproject',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_resume', to='resume.resume'),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.PositiveIntegerField(blank=True, null=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_reference', to='resume.reference')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_resume', to='resume.resume')),
            ],
            options={
                'ordering': ['-hierarchy'],
            },
        ),
    ]
