# Generated by Django 5.2.5 on 2025-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_resumeproject_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='institution',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
