# Generated by Django 5.2.5 on 2025-08-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_reference_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
