# Generated by Django 5.2.5 on 2025-08-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0012_alter_project_managers'),
        ('resume', '0012_alter_reference_email_alter_reference_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.PositiveIntegerField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_certificate', to='landing_spot.certification')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_resume', to='resume.resume')),
            ],
            options={
                'ordering': ['-hierarchy'],
            },
        ),
    ]
