# Generated by Django 5.2.2 on 2025-06-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeproject',
            options={'ordering': ['-hierarchy']},
        ),
    ]
