# Generated by Django 5.2.2 on 2025-06-05 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0007_experience_resume_des'),
        ('resume', '0008_resumeproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_projects', to='landing_spot.project'),
        ),
        migrations.AlterField(
            model_name='resumeproject',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_projects', to='resume.resume'),
        ),
    ]
