# Generated by Django 5.2.2 on 2025-06-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='static_resume_file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/img/resume/static/'),
        ),
    ]
