# Generated by Django 5.2.2 on 2025-06-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0008_experience_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='resume_achi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=20, null=True),
        ),
    ]
