# Generated by Django 5.2.2 on 2025-06-08 15:30

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0009_education_resume_achi_alter_experience_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
