# Generated by Django 5.2.2 on 2025-06-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_spot', '0010_alter_project_managers_project_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_slug',
            new_name='slug',
        ),
    ]
